/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pembayaran;

/**
 *
 * @author afkar
 */
public class mainwindowbyr extends javax.swing.JFrame {

    /**
     * Creates new form mainwindow
     */
    public mainwindowbyr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cash = new javax.swing.JMenuItem();
        qrish = new javax.swing.JMenuItem();
        ewallet = new javax.swing.JMenuItem();
        credit = new javax.swing.JMenuItem();
        debit = new javax.swing.JMenuItem();
        gopay = new javax.swing.JMenuItem();
        shopeepay = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DEMO APLIKASI PEMBAYARAN");

        jMenu1.setText("Pembayaran");

        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        jMenu1.add(cash);

        qrish.setText("QRIS");
        qrish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrishActionPerformed(evt);
            }
        });
        jMenu1.add(qrish);

        ewallet.setText("E-Wallet");
        ewallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ewalletActionPerformed(evt);
            }
        });
        jMenu1.add(ewallet);

        credit.setText("Credit Card");
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        jMenu1.add(credit);

        debit.setText("Debit Card");
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });
        jMenu1.add(debit);

        gopay.setText("Gopay");
        gopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gopayActionPerformed(evt);
            }
        });
        jMenu1.add(gopay);

        shopeepay.setText("ShopeePay");
        shopeepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopeepayActionPerformed(evt);
            }
        });
        jMenu1.add(shopeepay);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        new windowbayarcash().setVisible(true);
        dispose();
    }//GEN-LAST:event_cashActionPerformed

    private void qrishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrishActionPerformed
    new windowbayarqrish().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_qrishActionPerformed

    private void ewalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ewalletActionPerformed
        // TODO add your handling code here:
        new windowbayarewallet().setVisible(true);
        dispose();
    }//GEN-LAST:event_ewalletActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
        new windowcreditcard().setVisible(true);
        dispose();
    }//GEN-LAST:event_creditActionPerformed

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitActionPerformed
        // TODO add your handling code here:
        new windowdebitcard().setVisible(true);
        dispose();
    }//GEN-LAST:event_debitActionPerformed

    private void gopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gopayActionPerformed
        // TODO add your handling code here:
        new windowgopay().setVisible(true);
        dispose();
    }//GEN-LAST:event_gopayActionPerformed

    private void shopeepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopeepayActionPerformed
        // TODO add your handling code here:
        new windowshopee().setVisible(true);
        dispose();
    }//GEN-LAST:event_shopeepayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindowbyr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindowbyr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindowbyr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindowbyr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindowbyr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cash;
    private javax.swing.JMenuItem credit;
    private javax.swing.JMenuItem debit;
    private javax.swing.JMenuItem ewallet;
    private javax.swing.JMenuItem gopay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem qrish;
    private javax.swing.JMenuItem shopeepay;
    // End of variables declaration//GEN-END:variables
}
